name: "npm"

on:
  push:
    branches:
      - "v2"

jobs:
  deploy:
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
      deployments: write

    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
      - uses: "actions/setup-node@v4"
        with:
          node-version: "24"
          cache: "npm"
      - uses: "actions/checkout@v4"
        with:
          repository: "getprobo/probo"
          path: "probo"
      - run: npm ci
      - run: npm run check:docs
      - run: npm run docs:check-reference
        env:
          PROBO_REPO_PATH: ${{ github.workspace }}/probo
      - run: npm run build
        env:
          PUBLIC_POSTHOG_API_KEY: ${{ secrets.PUBLIC_POSTHOG_API_KEY }}
          PUBLIC_COOKIE_BANNER_ID: ${{ secrets.PUBLIC_COOKIE_BANNER_ID }}
          PUBLIC_COOKIE_BANNER_API_BASE_URL: ${{ secrets.PUBLIC_COOKIE_BANNER_API_BASE_URL }}
      - uses: "cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65" # v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=www-getprobo-com
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
